### PR TITLE
Add missing devDependencies

### PR DESCRIPTION
**Pull request by ericclemmons**
Now the demos work!

### CODE REVIEW

**Comment by Guria** [comment]
soryy haven't updated repo yet but `function tree` now lives in main cerebral repo https://github.com/cerebral/cerebral/tree/master/packages/function-tree

**Comment by ericclemmons** [comment]
:'(

**Comment by ericclemmons** [comment]
Please update the description to point users in that direction!

**Comment by Guria** [comment]
We moved recently. Readme will be updated soon. BTW, monorepo has this demo in a runnable way.

**Pull request closed without merging**
